package com.kyberswap.android.presentation.common

import java.math.BigInteger

const val DEFAULT_ACCEPT_RATE_PERCENTAGE = 3
const val PERM = "PERM"
val DEFAULT_MAX_AMOUNT: BigInteger = 2.toBigInteger().pow(255)
const val DEFAULT_WALLET_ID = "0x3fFFF2F4f6C0831FAC59534694ACd14AC2Ea501b"
const val DEFAULT_MARKET_RATE = 0
const val DEFAULT_EXPECTED_RATE = 0
val DEFAULT_GAS_LIMIT = 380_000.toBigInteger()
val DEFAULT_GAS_LIMIT_TRANSFER = 30_000.toBigInteger()
const val DEFAULT_NAME = "Untitled"
val DEFAULT_GAS_LIMIT_SEND_ETH = 30_000.toBigInteger()
val DEFAULT_GAS_LIMIT_SEND_TOKEN = 100_000.toBigInteger()
const val MIN_SUPPORT_SWAP_SOURCE_AMOUNT = 0.001
val KEEP_ETH_BALANCE_FOR_GAS = 600_000.toBigDecimal()
const val TRANSER_TOKEN_GAS_LIMIT_DEFAULT = 125_000
const val DIGIX_GAS_LIMIT_DEFAULT = 750_000
const val EXCHANGE_TOKEN_GAS_LIMIT_DEFAULT = 760_000
const val EXCHANGE_ETH_TOKEN_GAS_LIMIT_DEFAULT = 120_000
const val TRANSFER_TOKEN_GAS_LIMIT_DEFAULT = 125_000
const val TRANSFER_ETH_GAS_LIMIT_DEFAULT = 30_000
const val TRANSFER_GAS_LIMIT_DEFAULT = 100_000


