package com.kyberswap.android.util

const val ACTION_NAME = "action_name"
const val ACTION_VALUE = "action_value"
const val EVENT_NAME = "event_name"
const val RATING_DIALOG_EVENT = "rating_dialog_event"
const val OPEN_PLAY_STORE_EVENT = "open_play_store_event"
const val NOT_OPEN_STORE_EVENT = "not_open_store_event"
const val OPEN_TX_FROM_ALERT_EVENT = "open_tx_from_alert_event"
const val SWAP_EVENT = "swap_event"
const val TX_MINED_EVENT = "tx_mined_event"
const val TX_FAILED_EVENT = "tx_failed_event"
const val CLICK_WALLET_CONNECT_EVENT = "click_wallet_connect_event"
const val OPEN_WALLET_CONNECT_SCREEN_EVENT = "open_wallet_connect_screen_event"
const val DISCONNECT_WALLET_CONNECT_EVENT = "disconnect_wallet_connect_event"
const val FAIL_WALLET_CONNECT_EVENT = "fail_wallet_connect_event"
const val SWITCH_WALLET_WHEN_WALLET_CONNECT_EVENT = "switch_wallet_when_wallet_connect_event"
const val USER_CLICK_ITEM_SUGGESTION_EVENT = "user_click_item_suggestion_event"
const val USER_CLICK_EDIT_CONTACT_EVENT = "user_click_edit_contact_event"
const val USER_CLICK_ADD_CONTACT_EVENT = "user_click_add_contact_event"
const val USER_CLICK_DELETE_CONTACT_EVENT = "user_click_delete_contact_event"
const val USER_CLICK_MORE_CONTACT_EVENT = "user_click_more_contact_event"
const val USER_CLICK_RECENT_CONTACT_EVENT = "user_click_recent_contact_event"
const val USER_CLICK_SPEED_UP_TX_EVENT = "user_click_speed_up_tx_event"
const val USER_CLICK_SUBMIT_SPEED_UP_TX_EVENT = "user_click_submit_speed_up_tx_event"
const val USER_CLICK_CANCEL_TX_EVENT = "user_click_cancel_tx_event"
const val USER_CLICK_SUBMIT_CANCEL_TX_EVENT = "user_click_submit_cancel_tx_event"
const val TX_SPEED_UP_CANCEL_DROPPED_EVENT = "tx_dropped_event"
const val FAIL_CANCEL_TX_EVENT = "fail_cancel_tx"
const val FAIL_SPEED_UP_TX_EVENT = "fail_speed_up_tx"

const val USER_CLICK_BUY = "lo_user_click_buy"
const val USER_CLICK_SELL = "lo_user_click_sell"
const val USER_CLICK_BUY_SELL_ERROR = "lo_user_click_buy_sell_error"
const val USER_CLICK_PRICE_TEXT = "lo_user_click_price_tex"
const val USER_CLICK_MARKET_PRICE_TEXT = "lo_user_click_market_price_text"
const val USER_CLICK_25_PERCENT = "lo_user_click_25_percent"
const val USER_CLICK_50_PERCENT = "lo_user_click_50_percent"
const val USER_CLICK_100_PERCENT = "lo_user_click_100_percent"
const val USER_CLICK_LEARN_MORE = "lo_user_click_lear_more"
const val USER_CLICK_MANAGE_ORDER = "lo_user_click_manage_order"
const val USER_CLICK_CHART = "lo_user_click_chart"
const val USER_CLICK_CHOOSE_MARKET = "lo_user_click_choose_market"
const val USER_CLICK_LO_V1 = "lo_user_click_lo_v1"
const val USER_CLICK_FAV = "lo_user_click_fav"
const val USER_CLICK_SUBMIT_LO_V1 = "lo_user_click_submit_order_v1"
const val USER_CLICK_SUBMIT_LO_V1_WARNING = "lo_user_click_submit_order_v1_warning"
const val USER_CLICK_COVERT_ETH_WETH = "lo_user_click_convert_eth_weth"
const val USER_CLICK_COVERT_ETH_WETH_ERROR = "lo_user_click_convert_eth_weth_eror"
const val USER_CLICK_CANCEL_ORDER = "lo_user_click_cancel_order"
const val USER_CLICK_SUBMIT_ORDER_CONFIRM = "lo_user_click_submit_order_confirm"
const val USER_CLICK_SUBMIT_ORDER_CONFIRM_V1 = "lo_user_click_submit_order_confirm_v1"
const val USER_CLICK_CANCEL_RELATED_ORDERS = "lo_user_click_cancel_related_order"
const val USER_CLICK_CANCEL_SUBMIT_ORDER = "lo_user_click_cancel_submit_order"
const val USER_CLICK_CANCEL_SUBMIT_ORDER_V1 = "lo_user_click_cancel_submit_order_v1"

const val USER_CLICK_FAV_MARKET = "lo_user_click_fav_market"
const val USER_CLICK_ETH_MARKET = "lo_user_click_eth_market"
const val USER_CLICK_WBTC_MARKET = "lo_user_click_wbtc_market"
const val USER_CLICK_SEARCH = "lo_user_click_search"

const val USER_CLICK_DATA_TRANSFER_YES = "user_click_data_transfer_yes"
const val USER_CLICK_DATA_TRANSFER_NO = "user_click_data_transfer_no"
const val USER_CLICK_DATA_TRANSFER_NO_CONTINUE = "user_click_data_transfer_no_continue"
const val USER_CLICK_DATA_TRANSFER_DISMISS = "user_click_data_transfer_dismiss"
const val USER_TRANSFER_DATA_FORCE_LOGOUT = "user_transfer_data_force_logout"
const val USER_FORCE_LOGOUT = "user_force_logout"

const val RATING_DIALOG_ACTION = "rating_dialog_action"
const val OPEN_PLAY_STORE_ACTION = "open_play_store_action"
const val NO_THANK_ACTION = "no_thank_action"
const val OPEN_TX_PENDING_ACTION = "open_tx_pending_action"
const val OPEN_TX_MINED_ACTION = "open_tx_mined_action"
const val TRANSFER_ACTION_FROM_ALERT = "transfer_action_from_alert"
const val SWAP_ACTION_FROM_ALERT = "swap_action_from_alert"
const val SWAP_ACTION = "swap_action"
const val TRANSACTION_DETAIL_ACTION = "transaction_detail_action"
const val TX_FAILED_ACTION = "tx_failed_action"
const val CLICK_WALLET_CONNECT_ACTION = "click_wallet_connect_action"
const val APPROVE_WALLET_CONNECT_SESSION_ACTION = "approve_wallet_connect_session_action"
const val REJECT_WALLET_CONNECT_SESSION_ACTION = "reject_wallet_connect_session_action"
const val APPROVE_WALLET_CONNECT_ACTION = "approve_wallet_connect_action"
const val REJECT_WALLET_CONNECT_ACTION = "reject_wallet_connect_action"
const val APPROVE_WALLET_CONNECT_SIGN_ACTION = "approve_wallet_connect_sign_action"
const val REJECT_WALLET_CONNECT_SIGN_ACTION = "reject_wallet_connect_sign_action"
const val OPEN_SCAN_IN_WALLET_CONNECT_ACTION = "open_scan_in_wallet_connect_action"

const val BA_USER_CLICK_BUY_ETH = "ba_user_click_buy_eth" // BA - Balance
const val BA_USER_CLICK_COPY_WALLET_ADDRESS = "ba_user_click_copy_wallet_address"
const val BA_USER_OPEN_QR_CODE_WALLET_ADDRESS = "ba_user_open_qr_code_wallet_address"
const val SW_USER_CLICK_COPY_WALLET_ADDRESS = "sw_user_click_copy_wallet_address" // sw - SWAP
const val LO_USER_CLICK_COPY_WALLET_ADDRESS =
    "lo_user_click_copy_wallet_address" // lo - Limit Order
const val MN_USER_CLICK_COPY_WALLET_ADDRESS = "mn_user_click_copy_wallet_address" // mn - Menu
const val ST_USER_CLICK_FAQ = "st_user_click_faq" // st - Setting
const val CH_USER_CLICK_BUY_LIMIT_ORDER = "ch_user_click_buy_limit_order" // ch - Chart
const val CH_USER_CLICK_SELL_LIMIT_ORDER = "ch_user_click_sell_limit_order"


