package com.kyberswap.android.util

const val ACTION_NAME = "action_name"
const val ACTION_VALUE = "action_value"
const val EVENT_NAME = "event_name"
const val RATING_DIALOG_EVENT = "rating_dialog_event"
const val OPEN_PLAY_STORE_EVENT = "open_play_store_event"
const val NOT_OPEN_STORE_EVENT = "not_open_store_event"
const val OPEN_TX_FROM_ALERT_EVENT = "open_tx_from_alert_event"
const val SWAP_EVENT = "swap_event"
const val TX_MINED_EVENT = "tx_mined_event"
const val TX_FAILED_EVENT = "tx_failed_event"

const val RATING_DIALOG_ACTION = "rating_dialog_action"
const val OPEN_PLAY_STORE_ACTION = "open_play_store_action"
const val NO_THANK_ACTION = "no_thank_action"
const val OPEN_TX_PENDING_ACTION = "open_tx_pending_action"
const val OPEN_TX_MINED_ACTION = "open_tx_mined_action"
const val TRANSFER_ACTION_FROM_ALERT = "transfer_action_from_alert"
const val SWAP_ACTION_FROM_ALERT = "swap_action_from_alert"
const val SWAP_ACTION = "swap_action"
const val TRANSACTION_DETAIL_ACTION = "transaction_detail_action"
const val TX_FAILED_ACTION = "tx_failed_action"
