package com.kyberswap.android.util

import com.kyberswap.android.R


val tokenDrawableList = mapOf(
    "ETH" to R.drawable.eth,
    "WETH" to R.drawable.weth,
    "KNC" to R.drawable.knc,
    "DAI" to R.drawable.dai,
    "OMG" to R.drawable.omg,
    "SNT" to R.drawable.snt,
    "ELF" to R.drawable.elf,
    "POWR" to R.drawable.powr,
    "MANA" to R.drawable.mana,
    "BAT" to R.drawable.bat,
    "REQ" to R.drawable.req,
    "GTO" to R.drawable.gto,
    "RDN" to R.drawable.rdn,
    "APPC" to R.drawable.appc,
    "ENG" to R.drawable.eng,
    "BQX" to R.drawable.bqx,
    "ADX" to R.drawable.adx,
    "AST" to R.drawable.ast,
    "RCN" to R.drawable.rcn,
    "LINK" to R.drawable.link,
    "STORM" to R.drawable.storm,
    "IOST" to R.drawable.iost,
    "MOT" to R.drawable.mot,
    "ABT" to R.drawable.abt,
//    "ENJ" to R.drawable.enj,
    "AE" to R.drawable.ae,
    "BLZ" to R.drawable.blz,
    "ELEC" to R.drawable.elec,
    "BBO" to R.drawable.bbo,
    "POLY" to R.drawable.poly,
    "LBA" to R.drawable.lba,
    "CVC" to R.drawable.cvc,
    "WAX" to R.drawable.wax,
    "POE" to R.drawable.poe,
    "PAY" to R.drawable.pay,
    "DTA" to R.drawable.dta,
    "BNT" to R.drawable.bnt,
    "TUSD" to R.drawable.tusd,
    "LEND" to R.drawable.lend,
    "WINGS" to R.drawable.wings,
    "MTL" to R.drawable.mtl,
    "WABI" to R.drawable.wabi,
//    "COFI" to R.drawable.cofi,
    "MOC" to R.drawable.moc,
    "REP" to R.drawable.rep,
    "ZRX" to R.drawable.zrx,
    "MAS" to R.drawable.mas,
    "DAT" to R.drawable.dat,
    "REN" to R.drawable.ren,
    "QKC" to R.drawable.qkc,
    "MKR" to R.drawable.mkr,
    "DCC" to R.drawable.dcc,
    "SSP" to R.drawable.ssp,
    "PRO" to R.drawable.pro,
    "OCN" to R.drawable.ocn,
    "EKO" to R.drawable.eko,
    "OST" to R.drawable.ost,
    "DTH" to R.drawable.dth,
    "PT" to R.drawable.pt,
    "INF" to R.drawable.inf,
    "TTC" to R.drawable.ttc,
    "ABYSS" to R.drawable.abyss,
    "WBTC" to R.drawable.wbtc,
    "MLN" to R.drawable.mln,
    "USDC" to R.drawable.usdc,
    "EURS" to R.drawable.eurs,
    "BIX" to R.drawable.bix,
    "CDT" to R.drawable.cdt,
    "MCO" to R.drawable.mco
//    "PAX" to R.drawable.pax,
)